### ISSUE TITLE
Error creating machine on OTE platform

### ISSUE THREAD

**Issue by murraybiscuit** [Gandi/docker-machine-gandi#9]
I'm trying this for the first time using the OTE platform, along with provided code in the readme for testing. 
I'm using it on Windows (yes, I know, why would you use Windows?).
I'm getting an error:

```
$ docker-machine create --engine-storage-driver overlay --driver gandi --gandi-api-key=xxxxxx --gandi-url=https://rpc.ote.gandi.net/xmlrpc/ ubuntu-machine
Running pre-create checks...
Creating machine...
(ubuntu-machine) Creating Gandi server...
Error creating machine: Error in driver during machine creation: error: "Error on object : OBJECT_UN
KNOWN (CAUSE_FAILURE) [(OperationalError) (1054, "Unknown column 'rproxy.hosting_account_id' in 'fie
ld list'")]" code: 500066
```

Thoughts?

**Comment by gdchamal** [comment]
Hello, OTE platform is not able to support this docker-machine driver as it does not have an usable Iaas platform to spwan virtual machine.

Obviously there is a bug on the OTE platform and error should be user friendly rather than this one.

If you need credits for testing on our production datacenters, ping me back.

**Comment by murraybiscuit** [comment]
Thanks for the feedback. 
Agreed with the more descriptive error from the OTE platform.
More helpful, I think would to add the limitation to the bullets in the OT&E section of the API docs as well...
http://doc.rpc.gandi.net/overview.html#ot-e-system
The docs are generally the starting point, so if I had known earlier, I could have saved some time.
